// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN9jAyoW--zA3mOTG6sSJCGnCUS7lkFh4',
    appId: '1:133582725260:android:92203f037aafb593c19ba9',
    messagingSenderId: '133582725260',
    projectId: 'votetracker-ba993',
    storageBucket: 'votetracker-ba993.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6Bky8K4taiDwqme2mouvY8c573uG3-I',
    appId: '1:133582725260:web:181e7657b648e6adc19ba9',
    messagingSenderId: '133582725260',
    projectId: 'votetracker-ba993',
    authDomain: 'votetracker-ba993.firebaseapp.com',
    storageBucket: 'votetracker-ba993.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZQd8ddWkndEONlYRZwWzfSsA8woSCWU',
    appId: '1:133582725260:ios:441410b80502798ac19ba9',
    messagingSenderId: '133582725260',
    projectId: 'votetracker-ba993',
    storageBucket: 'votetracker-ba993.appspot.com',
    iosBundleId: 'com.example.voteTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZQd8ddWkndEONlYRZwWzfSsA8woSCWU',
    appId: '1:133582725260:ios:441410b80502798ac19ba9',
    messagingSenderId: '133582725260',
    projectId: 'votetracker-ba993',
    storageBucket: 'votetracker-ba993.appspot.com',
    iosBundleId: 'com.example.voteTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq6Bky8K4taiDwqme2mouvY8c573uG3-I',
    appId: '1:133582725260:web:fee7867eb625d18bc19ba9',
    messagingSenderId: '133582725260',
    projectId: 'votetracker-ba993',
    authDomain: 'votetracker-ba993.firebaseapp.com',
    storageBucket: 'votetracker-ba993.appspot.com',
  );

}